# Generated by Django 4.1.5 on 2023-02-23 00:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Items",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ItemName", models.CharField(max_length=50)),
                ("ItemDiscription", models.TextField()),
                ("ItemMarkup", models.FloatField()),
                ("SalePrice", models.FloatField()),
                ("PriceToOrder", models.FloatField()),
                ("InStock", models.IntegerField()),
                (
                    "ProductType",
                    models.CharField(
                        choices=[
                            ("Fresh Produce", "PRODUCE"),
                            ("Canned Goods", "CANNED"),
                            ("Frozen", "FROZEN"),
                            ("Dairy", "DAIRY"),
                            ("Deli", "DELI"),
                            ("Bakery", "BAKERY"),
                            ("Stationary", "STATIONARY"),
                            ("Jewelry", "JEWELERY"),
                            ("Crafts", "CRAFTS"),
                            ("Electronics", "ELECTRONICS"),
                            ("Men's Clothing", "MENS"),
                            ("Women's Clothing", "WOMENS"),
                            ("Toys", "TOYS"),
                            ("Cleaning Supplies", "CLEANING"),
                            ("Housewares", "HOUSEWARES"),
                            ("Hardware", "HARDWARE"),
                            ("Gardening", "GARDEN"),
                            ("Cosmetics", "COSMETICS"),
                            ("Pharmacy", "PHARMACY"),
                            ("Sporting Goods", "SPORTING"),
                            ("Automotive", "AUTOMOTIVE"),
                            ("Impulse", "IMPULSE"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ItemSupplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("SupplierName", models.CharField(max_length=100)),
                ("ValueSuppliedToDate", models.FloatField()),
                ("FirstItemDate", models.DateField()),
                ("LastItemDate", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("TransTotal", models.FloatField()),
                ("BuyOnline", models.BooleanField()),
                ("buyOffline", models.BooleanField()),
                (
                    "CustomerID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.customer"
                    ),
                ),
                (
                    "ItemID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.items"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="items",
            name="ItemSupplierID",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="home.itemsupplier"
            ),
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("img", models.ImageField(upload_to="images/")),
                (
                    "ItemsID",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.items",
                    ),
                ),
            ],
            options={
                "db_table": "Image Upload",
            },
        ),
    ]
