# Generated by Django 4.1.5 on 2023-02-23 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='ProductType',
            field=models.CharField(choices=[('Fresh Produce', 'PRODUCE'), ('Canned Goods', 'CANNED'), ('Frozen', 'FROZEN'), ('Dairy', 'DAIRY'), ('Deli', 'DELI'), ('Bakery', 'BAKERY'), ('Stationary', 'STATIONARY'), ('Jewelry', 'JEWELERY'), ('Crafts', 'CRAFTS'), ('Electronics', 'ELECTRONICS'), ("Men's Clothing", 'MENS'), ("Women's Clothing", 'WOMENS'), ('Toys', 'TOYS'), ('Cleaning Supplies', 'CLEANING'), ('Housewares', 'HOUSEWARES'), ('Hardware', 'HARDWARE'), ('Gardening', 'GARDEN'), ('Cosmetics', 'COSMETICS'), ('Pharmacy', 'PHARMACY'), ('Sporting Goods', 'SPORTING'), ('Automotive', 'AUTOMOTIVE'), ('Impulse', 'IMPULSE')], max_length=50, null=True),
        ),
    ]
