# Generated by Django 4.1.5 on 2023-01-31 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("FirstName", models.CharField(max_length=30)),
                ("LastName", models.CharField(max_length=30)),
                ("City", models.CharField(max_length=50)),
                ("State", models.CharField(max_length=2)),
                ("Zip", models.IntegerField()),
                ("email", models.CharField(max_length=100)),
                ("ChardNum", models.IntegerField()),
                ("PhoneNum", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Items",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ItemName", models.CharField(max_length=50)),
                ("ItemDiscription", models.TextField()),
                ("ItemMarkup", models.FloatField()),
                ("SalePrice", models.FloatField()),
                ("PriceToOrder", models.FloatField()),
                ("InStock", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="ItemSupplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("SupplierName", models.CharField(max_length=100)),
                ("ValueSuppliedToDate", models.DateField()),
                ("FirstItemDate", models.DateField()),
                ("LastItemDate", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("TransTotal", models.FloatField()),
                ("BuyOnline", models.BooleanField()),
                ("buyOffline", models.BooleanField()),
                (
                    "CustomerId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.customer"
                    ),
                ),
                (
                    "EmployeeID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.employee"
                    ),
                ),
                (
                    "ItemID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.items"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="items",
            name="ItemSupplierID",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="home.itemsupplier"
            ),
        ),
    ]
