# Generated by Django 4.1.5 on 2023-02-27 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="BuyOnline",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="buyOffline",
        ),
        migrations.AddField(
            model_name="customer",
            name="cart",
            field=models.ManyToManyField(default=None, to="home.items"),
        ),
        migrations.AddField(
            model_name="transaction",
            name="Address",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="transaction",
            name="Phone",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="transaction",
            name="Quantity",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="transaction",
            name="Status",
            field=models.BooleanField(default=True),
        ),
    ]
