# Generated by Django 4.1.5 on 2023-01-31 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_customer_items_itemsupplier_transaction_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction",
            old_name="CustomerId",
            new_name="CustomerID",
        ),
    ]
