# Generated by Django 4.1.5 on 2023-03-01 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_transaction_buyonline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='itemImage',
            field=models.URLField(default='https://t3.ftcdn.net/jpg/03/45/05/92/360_F_345059232_CPieT8RIWOUk4JqBkkWkIETYAkmz2b75.jpg', max_length=500),
        ),
    ]
