# Generated by Django 4.1.5 on 2023-02-01 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_rename_customerid_transaction_customerid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemsupplier",
            name="ValueSuppliedToDate",
            field=models.FloatField(),
        ),
    ]
