# Generated by Django 4.1.5 on 2023-03-01 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_items_itemimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
