# Generated by Django 4.1.5 on 2023-03-03 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_remove_itemsupplier_id_customer_cart_itemsupplier_id"),
        ("home", "0004_delete_image"),
    ]

    operations = []
