# Generated by Django 4.1.5 on 2023-02-01 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_rename_chardnum_customer_cardnum"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="CardNum",
        ),
    ]
