# Generated by Django 4.1.5 on 2023-02-13 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_remove_customer_cardnum"),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("img", models.ImageField(upload_to="images/")),
            ],
            options={
                "db_table": "Image Upload",
            },
        ),
        migrations.AlterField(
            model_name="items",
            name="InStock",
            field=models.IntegerField(),
        ),
    ]
