# Generated by Django 4.1.5 on 2023-02-13 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_image_alter_items_instock"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="ItemsID",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="home.items"
            ),
        ),
    ]
