# Generated by Django 4.1.5 on 2023-02-13 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0008_image_itemsid"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="Password",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="Password",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
