# Generated by Django 4.1.5 on 2023-02-16 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0009_customer_password_employee_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='City',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='FirstName',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='LastName',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='Password',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='PhoneNum',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='State',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='Zip',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
